### PR TITLE
applyNT

### PR DESCRIPTION
**Pull request by phadej**
Taken from my previous PR into separate one.

Mostly to demonstrate it only works on 7.10.3, not 7.8.4 or 8.0.1. See travis.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Oh dear! The GHC 7.8.4 failure seems simple enough to fix (just change `trans = id` to `trans x = x`), but the GHC 8.0.1 failure seems much more dire. (And if we can't get that example to typecheck, that undermines the entire purpose of adding `applyNT` in the first place!)

Is this a `RankNTypes`-related typechecker regression, I wonder? I seem to get the same error on GHC 8.0.2 and HEAD as well.

**Comment by RyanGlScott** [comment]
I've opened [GHC Trac #12749](https://ghc.haskell.org/trac/ghc/ticket/12749) for this issue.

**Comment by phadej** [comment]
@RyanGlScott I was just suggesting to make a ticket.

I don't know how https://mail.haskell.org/pipermail/ghc-devs/2016-September/012940.html message is related. After all `if b then trans else applyNT` type is polymorphic, but SPJ proposes to never unify a type variable with a polymorphic type...

_EDIT_ let's have discussion on the GHC ticket.

**Comment by RyanGlScott** [comment]
Well, this is awkward. [GHC Trac #12749](https://ghc.haskell.org/trac/ghc/ticket/12749) was closed as invalid because this is a known shortcoming of `RankNTypes`, and the expression `(if b then trans else applyNT) eitherToMaybe` only typechecked on GHC 7.10.3 and earlier due to a fluke.

As SPJ [recommended](https://ghc.haskell.org/trac/ghc/ticket/12749#comment:2), you could make that expression typecheck by doing some slight refactoring:

``` haskell
applyNTCheck :: NatTrans (Either a) Maybe
applyNTCheck = ((if b then trans else applyNT) 
                     :: NatTrans (Either a) Maybe 
                     -> NatTrans (Either a) Maybe)
                eitherToMaybe
```

But if you do this, do you even need `applyNT` anymore? You can also write the above expression as:

``` haskell
applyNTCheck :: NatTrans (Either a) Maybe
applyNTCheck = ((if b then trans else id) 
                     :: NatTrans (Either a) Maybe 
                     -> NatTrans (Either a) Maybe)
                eitherToMaybe
```

It won't typecheck on GHC 7.8.4, but it will on GHC 7.10.3 and later! So it turns out `applyNT` has much less limited utility than I previously imagined.

It's possible that `applyNT` might be useful in other scenarios, although I can't think of one off the top of my head.

**Comment by phadej** [comment]
Can you make a `0.4` release? I'd say we can hold with `applyNT`, until we know where it can be useful?

**Comment by andygill** [comment]
Does this compile with 8.0.1? Travis seems to say no.

**Comment by phadej** [comment]
@andygill See https://ghc.haskell.org/trac/ghc/ticket/12749, this PR includes a test that motivated creation of `applyNT`, but it seems it worked in GHC-7.x by accident, due a bug.

I'll close this PR.

**Pull request closed without merging**
