### PR TITLE
Added instances for Yoneda, Coyoneda and Ran

### PR DESCRIPTION
**Pull request by roboguy13**
I think these are correct. If so, it comes down to whether or not they are too strange and whether you want to depend `kan-extensions`.

These are all specifically natural transformations from a reader functor (or, in the case of `Ran`, reader-like functor).

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Looks good to me. GHC 7.6 won't accept the type signature of your `Coyoneda` instance due to an unfortunate GHC bug, so I'd just opt for not using `InstanceSigs` altogether.

The GHC HEAD error should be fixed on the `master` branch now, if you want to pull that.

**Comment by andygill** [comment]
I'm wanting to pull this into its own repo (/ different repo somewhere) rather than include these instances here. I like the code, but a key property of the package it its depends on almost nothing. Further, we should think about what should be an instance of Transformation; there may be others.

Thoughts?

(Nice find with the instances, by the way!)

**Comment by roboguy13** [comment]
Would we run into problems with orphan instances if we did that? Other than that, that sounds good to me. It makes sense that this package should have a bare minimum of dependencies.

**Comment by RyanGlScott** [comment]
> Would we run into problems with orphan instances if we did that?

We would, but it's unlikely that @ekmett would want to put these instances into `kan-extensions` itself, so an orphan instance package is just about the only option.

As long as the package (`natural-transformation-instances`?) clearly indicates that it exports orphans (_à la_ `base-orphans`, `transformers-compat`, `vector-instances`, etc.), it should be okay.

**Comment by roboguy13** [comment]
An orphan instance package sounds like a good way to go about it. I also added instances for `Codensity` and `Density` (which are to `Monad` and `Comonad` what `Yoneda` and `Coyoneda` are to `Functor`s) and put that in the `kan` branch for the time being.

Incidentally, all those data types (as I understand them) perform a sort of optimization of the underlying `Functor`/`Monad`/`Comonad`, so I feel like there is probably some kind of practical motivation to have these instances (although, I'm not totally sure what it would be at the moment). I think the optimization is similar to the Hughes list/difference list optimization.

**Comment by ekmett** [comment]
http://arxiv.org/abs/1406.4823 explains the difference list connection in depth.

**Comment by andygill** [comment]
I'm going to revert this, and encourage @roboguy13 to have a new package that has the orphans. It allows the natural transformation package depend on nothing else.

**Pull request merged**
